acled_url: https://api.acleddata.com/acled/read
em_dat_url: https://public.emdat.be/login
hdi_url: https://hdr.undp.org/sites/default/files/2023-24_HDR/HDR23-24_Composite_indices_complete_time_series.csv


